#define MAX_MESSAGE_LEN 105
#define MESSAGE_END "/sys/kernel/uartstream/message_end"
#define MESSAGE_LEN "/sys/kernel/uartstream/message_length"
#define MESSAGE_ERROR "/sys/kernel/uartstream/message_error"


const char *wakeline_data[4] = {
	"/sys/kernel/wakeline//wakeline_enable",
	"/sys/kernel/wakeline//wakeline_disable",
	"/sys/kernel/wakeline//wakeline_ack_enable",
	"/sys/kernel/wakeline//wakeline_ack_disable"
};


const char *char_values[MAX_MESSAGE_LEN] = {
	"/sys/kernel/uartstream/char1" ,
        "/sys/kernel/uartstream/char2" ,
        "/sys/kernel/uartstream/char3" ,
        "/sys/kernel/uartstream/char4" ,
        "/sys/kernel/uartstream/char5" ,
        "/sys/kernel/uartstream/char6" ,
        "/sys/kernel/uartstream/char7" ,
        "/sys/kernel/uartstream/char8" ,
        "/sys/kernel/uartstream/char9" ,
        "/sys/kernel/uartstream/char10" ,
        "/sys/kernel/uartstream/char11" ,
        "/sys/kernel/uartstream/char12" ,
        "/sys/kernel/uartstream/char13" ,
        "/sys/kernel/uartstream/char14" ,
        "/sys/kernel/uartstream/char15" ,
        "/sys/kernel/uartstream/char16" ,
        "/sys/kernel/uartstream/char17" ,
        "/sys/kernel/uartstream/char18" ,
        "/sys/kernel/uartstream/char19" ,
        "/sys/kernel/uartstream/char20" ,
        "/sys/kernel/uartstream/char21" ,
        "/sys/kernel/uartstream/char22" ,
        "/sys/kernel/uartstream/char23" ,
        "/sys/kernel/uartstream/char24" ,
        "/sys/kernel/uartstream/char25" ,
        "/sys/kernel/uartstream/char26" ,
        "/sys/kernel/uartstream/char27" ,
        "/sys/kernel/uartstream/char28" ,
        "/sys/kernel/uartstream/char29" ,
        "/sys/kernel/uartstream/char30" ,
        "/sys/kernel/uartstream/char31" ,
        "/sys/kernel/uartstream/char32" ,
        "/sys/kernel/uartstream/char33" ,
        "/sys/kernel/uartstream/char34" ,
        "/sys/kernel/uartstream/char35" ,
        "/sys/kernel/uartstream/char36" ,
        "/sys/kernel/uartstream/char37" ,
        "/sys/kernel/uartstream/char38" ,
        "/sys/kernel/uartstream/char39" ,
        "/sys/kernel/uartstream/char40" ,
        "/sys/kernel/uartstream/char41" ,
        "/sys/kernel/uartstream/char42" ,
        "/sys/kernel/uartstream/char43" ,
        "/sys/kernel/uartstream/char44" ,
        "/sys/kernel/uartstream/char45" ,
        "/sys/kernel/uartstream/char46" ,
        "/sys/kernel/uartstream/char47" ,
        "/sys/kernel/uartstream/char48" ,
        "/sys/kernel/uartstream/char49" ,
        "/sys/kernel/uartstream/char50" ,
        "/sys/kernel/uartstream/char51" ,
        "/sys/kernel/uartstream/char52" ,
        "/sys/kernel/uartstream/char53" ,
        "/sys/kernel/uartstream/char54" ,
        "/sys/kernel/uartstream/char55" ,
        "/sys/kernel/uartstream/char56" ,
        "/sys/kernel/uartstream/char57" ,
        "/sys/kernel/uartstream/char58" ,
        "/sys/kernel/uartstream/char59" ,
        "/sys/kernel/uartstream/char60" ,
        "/sys/kernel/uartstream/char61" ,
        "/sys/kernel/uartstream/char62" ,
        "/sys/kernel/uartstream/char63" ,
        "/sys/kernel/uartstream/char64" ,
        "/sys/kernel/uartstream/char65" ,
        "/sys/kernel/uartstream/char66" ,
        "/sys/kernel/uartstream/char67" ,
        "/sys/kernel/uartstream/char68" ,
        "/sys/kernel/uartstream/char69" ,
        "/sys/kernel/uartstream/char70" ,
        "/sys/kernel/uartstream/char71" ,
        "/sys/kernel/uartstream/char72" ,
        "/sys/kernel/uartstream/char73" ,
        "/sys/kernel/uartstream/char74" ,
        "/sys/kernel/uartstream/char75" ,
        "/sys/kernel/uartstream/char76" ,
        "/sys/kernel/uartstream/char77" ,
        "/sys/kernel/uartstream/char78" ,
        "/sys/kernel/uartstream/char79" ,
        "/sys/kernel/uartstream/char80" ,
        "/sys/kernel/uartstream/char81" ,
        "/sys/kernel/uartstream/char82" ,
        "/sys/kernel/uartstream/char83" ,
        "/sys/kernel/uartstream/char84" ,
        "/sys/kernel/uartstream/char85" ,
        "/sys/kernel/uartstream/char86" ,
        "/sys/kernel/uartstream/char87" ,
        "/sys/kernel/uartstream/char88" ,
        "/sys/kernel/uartstream/char89" ,
        "/sys/kernel/uartstream/char90" ,
        "/sys/kernel/uartstream/char91" ,
        "/sys/kernel/uartstream/char92" ,
        "/sys/kernel/uartstream/char93" ,
        "/sys/kernel/uartstream/char94" ,
        "/sys/kernel/uartstream/char95" ,
        "/sys/kernel/uartstream/char96" ,
        "/sys/kernel/uartstream/char97" ,
        "/sys/kernel/uartstream/char98" ,
        "/sys/kernel/uartstream/char99" ,
        "/sys/kernel/uartstream/char100" ,
        "/sys/kernel/uartstream/char101" ,
        "/sys/kernel/uartstream/char102" ,
        "/sys/kernel/uartstream/char103" ,
        "/sys/kernel/uartstream/char104" ,
        "/sys/kernel/uartstream/char105"
};


const char *char_timestamps[MAX_MESSAGE_LEN] = {
	"/sys/kernel/uartstream/char1_timestamp" ,
        "/sys/kernel/uartstream/char2_timestamp" ,
        "/sys/kernel/uartstream/char3_timestamp" ,
        "/sys/kernel/uartstream/char4_timestamp" ,
        "/sys/kernel/uartstream/char5_timestamp" ,
        "/sys/kernel/uartstream/char6_timestamp" ,
        "/sys/kernel/uartstream/char7_timestamp" ,
        "/sys/kernel/uartstream/char8_timestamp" ,
        "/sys/kernel/uartstream/char9_timestamp" ,
        "/sys/kernel/uartstream/char10_timestamp" ,
        "/sys/kernel/uartstream/char11_timestamp" ,
        "/sys/kernel/uartstream/char12_timestamp" ,
        "/sys/kernel/uartstream/char13_timestamp" ,
        "/sys/kernel/uartstream/char14_timestamp" ,
        "/sys/kernel/uartstream/char15_timestamp" ,
        "/sys/kernel/uartstream/char16_timestamp" ,
        "/sys/kernel/uartstream/char17_timestamp" ,
        "/sys/kernel/uartstream/char18_timestamp" ,
        "/sys/kernel/uartstream/char19_timestamp" ,
        "/sys/kernel/uartstream/char20_timestamp" ,
        "/sys/kernel/uartstream/char21_timestamp" ,
        "/sys/kernel/uartstream/char22_timestamp" ,
        "/sys/kernel/uartstream/char23_timestamp" ,
        "/sys/kernel/uartstream/char24_timestamp" ,
        "/sys/kernel/uartstream/char25_timestamp" ,
        "/sys/kernel/uartstream/char26_timestamp" ,
        "/sys/kernel/uartstream/char27_timestamp" ,
        "/sys/kernel/uartstream/char28_timestamp" ,
        "/sys/kernel/uartstream/char29_timestamp" ,
        "/sys/kernel/uartstream/char30_timestamp" ,
        "/sys/kernel/uartstream/char31_timestamp" ,
        "/sys/kernel/uartstream/char32_timestamp" ,
        "/sys/kernel/uartstream/char33_timestamp" ,
        "/sys/kernel/uartstream/char34_timestamp" ,
        "/sys/kernel/uartstream/char35_timestamp" ,
        "/sys/kernel/uartstream/char36_timestamp" ,
        "/sys/kernel/uartstream/char37_timestamp" ,
        "/sys/kernel/uartstream/char38_timestamp" ,
        "/sys/kernel/uartstream/char39_timestamp" ,
        "/sys/kernel/uartstream/char40_timestamp" ,
        "/sys/kernel/uartstream/char41_timestamp" ,
        "/sys/kernel/uartstream/char42_timestamp" ,
        "/sys/kernel/uartstream/char43_timestamp" ,
        "/sys/kernel/uartstream/char44_timestamp" ,
        "/sys/kernel/uartstream/char45_timestamp" ,
        "/sys/kernel/uartstream/char46_timestamp" ,
        "/sys/kernel/uartstream/char47_timestamp" ,
        "/sys/kernel/uartstream/char48_timestamp" ,
        "/sys/kernel/uartstream/char49_timestamp" ,
        "/sys/kernel/uartstream/char50_timestamp" ,
        "/sys/kernel/uartstream/char51_timestamp" ,
        "/sys/kernel/uartstream/char52_timestamp" ,
        "/sys/kernel/uartstream/char53_timestamp" ,
        "/sys/kernel/uartstream/char54_timestamp" ,
        "/sys/kernel/uartstream/char55_timestamp" ,
        "/sys/kernel/uartstream/char56_timestamp" ,
        "/sys/kernel/uartstream/char57_timestamp" ,
        "/sys/kernel/uartstream/char58_timestamp" ,
        "/sys/kernel/uartstream/char59_timestamp" ,
        "/sys/kernel/uartstream/char60_timestamp" ,
        "/sys/kernel/uartstream/char61_timestamp" ,
        "/sys/kernel/uartstream/char62_timestamp" ,
        "/sys/kernel/uartstream/char63_timestamp" ,
        "/sys/kernel/uartstream/char64_timestamp" ,
        "/sys/kernel/uartstream/char65_timestamp" ,
        "/sys/kernel/uartstream/char66_timestamp" ,
        "/sys/kernel/uartstream/char67_timestamp" ,
        "/sys/kernel/uartstream/char68_timestamp" ,
        "/sys/kernel/uartstream/char69_timestamp" ,
        "/sys/kernel/uartstream/char70_timestamp" ,
        "/sys/kernel/uartstream/char71_timestamp" ,
        "/sys/kernel/uartstream/char72_timestamp" ,
        "/sys/kernel/uartstream/char73_timestamp" ,
        "/sys/kernel/uartstream/char74_timestamp" ,
        "/sys/kernel/uartstream/char75_timestamp" ,
        "/sys/kernel/uartstream/char76_timestamp" ,
        "/sys/kernel/uartstream/char77_timestamp" ,
        "/sys/kernel/uartstream/char78_timestamp" ,
        "/sys/kernel/uartstream/char79_timestamp" ,
        "/sys/kernel/uartstream/char80_timestamp" ,
        "/sys/kernel/uartstream/char81_timestamp" ,
        "/sys/kernel/uartstream/char82_timestamp" ,
        "/sys/kernel/uartstream/char83_timestamp" ,
        "/sys/kernel/uartstream/char84_timestamp" ,
        "/sys/kernel/uartstream/char85_timestamp" ,
        "/sys/kernel/uartstream/char86_timestamp" ,
        "/sys/kernel/uartstream/char87_timestamp" ,
        "/sys/kernel/uartstream/char88_timestamp" ,
        "/sys/kernel/uartstream/char89_timestamp" ,
        "/sys/kernel/uartstream/char90_timestamp" ,
        "/sys/kernel/uartstream/char91_timestamp" ,
        "/sys/kernel/uartstream/char92_timestamp" ,
        "/sys/kernel/uartstream/char93_timestamp" ,
        "/sys/kernel/uartstream/char94_timestamp" ,
        "/sys/kernel/uartstream/char95_timestamp" ,
        "/sys/kernel/uartstream/char96_timestamp" ,
        "/sys/kernel/uartstream/char97_timestamp" ,
        "/sys/kernel/uartstream/char98_timestamp" ,
        "/sys/kernel/uartstream/char99_timestamp" ,
        "/sys/kernel/uartstream/char100_timestamp" ,
        "/sys/kernel/uartstream/char101_timestamp" ,
        "/sys/kernel/uartstream/char102_timestamp" ,
        "/sys/kernel/uartstream/char103_timestamp" ,
        "/sys/kernel/uartstream/char104_timestamp" ,
        "/sys/kernel/uartstream/char105_timestamp"
};








